// <auto-generated />
namespace DataLayrer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Add_AdminLogins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AdminLogins));
        
        string IMigrationMetadata.Id
        {
            get { return "202206290643579_Add_AdminLogins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
